### ISSUE TITLE
Multi-account and regions

### ISSUE THREAD

**Issue by baron42bba** [mattusifer/s3ed#21]
Thanks a lot for working on this module!
I think support for using different accounts/profiles and regions would be a big plus.
Eg have the path start with /profile/region/
Then it can be different for each interaction with s3 without much hassle.

**Comment by mattusifer** [comment]
Thanks for your feedback! I agree, I think adding support for switching profiles would be a great feature to have down the line.

In it's current form, this package is just calls into the `aws` CLI and uses whatever the default profile is there - it doesn't provide any easy way to switch profiles from within emacs. Nevertheless, changing profiles and invoking s3ed again shouldn't have any negative side effects - this package clears out the s3ed tmp directory between s3ed operations. 

I have plans to turn this into a major mode and separate it out from dired so that it is more stable and reliable, so that is my highest priority with this right now. Once that is done I'll look into adding more features such as this one.
